on: push

name: Continuous integration

jobs:
  CI:
    runs-on: ubuntu-latest
    name: Rust project
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain <Stable>
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustc, cargo, rustfmt, rust-std, clippy
      - name: Security audit for crates
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test (to fix coverage?)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
      - uses: actions-rs/grcov@v0.1
      - name: Checking format with rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Linting with clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
