on: push

name: Continuous integration

jobs:
  CI:
    runs-on: ubuntu-latest
    name: Rust project
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain <Stable>
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustc, cargo, rustfmt, rust-std, clippy
      - name: Security audit for crates
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Test (to fix coverage?)
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Checking format with rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Linting with clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
